databases:
  - name: postgres
    plan: free
    region: frankfurt
    ipAllowList: []
    databaseName: db
    user: postgres
    postgresMajorVersion: "16"

services:
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: backend
    env: docker
    plan: free
    image:
      url: ghcr.io/efrei-m1-dev/projetfinal-messagerie-choco-fred-sofiane:backend-latest
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PASSWORD
        value: ${REDIS_PASSWORD}
      - key: PORT
        value: ${BACKEND_PORT}
    dockerCommand: "npm run start"


