name: messagerie-choco-fred-sofiane
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  db:
    image: postgres:latest
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    image: ghcr.io/efrei-m1-dev/projetfinal-messagerie-choco-fred-sofiane:backend-latest
    restart: always
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/${DATABASE_NAME}"
      REDIS_HOST: redis
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      PORT: "${BACKEND_PORT}"
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
  cache:
    driver: local
