name: Build-Publish-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        id: convert_repository
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=owner::${OWNER}"
          echo "::set-output name=repo::${REPO}"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image backend
        run: docker build -t ghcr.io/${{ steps.convert_repository.outputs.owner }}/${{ steps.convert_repository.outputs.repo }}:backend-latest ./backend

      - name: Build Docker image frontend
        run: docker build -t ghcr.io/${{ steps.convert_repository.outputs.owner }}/${{ steps.convert_repository.outputs.repo }}:frontend-latest ./frontend

      - name: Push Docker image to GitHub Container Registry (backend)
        run: docker push ghcr.io/${{ steps.convert_repository.outputs.owner }}/${{ steps.convert_repository.outputs.repo }}:backend-latest

      - name: Push Docker image to GitHub Container Registry (frontend)
        run: docker push ghcr.io/${{ steps.convert_repository.outputs.owner }}/${{ steps.convert_repository.outputs.repo }}:frontend-latest


      #Pour le déploiement sur le VPS
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy docker-compose and .env to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "docker/docker-compose.yml,.env"
          target: "/home/${{ secrets.VPS_USERNAME }}/app/projetFinal"

      - name: SSH into VPS and deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/app/projetFinal/docker
            docker-compose --env-file ../.env -f docker-compose.yml up -d


        #Pour le déploiement sur Render
      - name: Deploy backend to Render
        uses: render-deploy-action@1.0.0
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}
        run: |
          curl "$deploy_url"

      - name: Deploy frontend to Render
        uses: render-deploy-action@1.0.0
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL_FRONTEND }}
        run: |
          curl "$deploy_url"