name: Build-Publish-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        id: convert_repository
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=owner::${OWNER}"
          echo "::set-output name=repo::${REPO}"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image backend
        run: docker build -t ghcr.io/${{ steps.convert_repository.outputs.owner }}/${{ steps.convert_repository.outputs.repo }}:backend-latest ./backend

      - name: Build Docker image frontend
        run: docker build -t ghcr.io/${{ steps.convert_repository.outputs.owner }}/${{ steps.convert_repository.outputs.repo }}:frontend-latest ./frontend

      - name: Push Docker image to GitHub Container Registry (backend)
        run: docker push ghcr.io/${{ steps.convert_repository.outputs.owner }}/${{ steps.convert_repository.outputs.repo }}:backend-latest

      - name: Push Docker image to GitHub Container Registry (frontend)
        run: docker push ghcr.io/${{ steps.convert_repository.outputs.owner }}/${{ steps.convert_repository.outputs.repo }}:frontend-latest

      # Pour le déploiement sur Render
      - name: Deploy backend to Render
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}"

      - name: Deploy frontend to Render
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL_FRONTEND }}"
